version: '3'
services:

  elasticsearch:
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    restart: unless-stopped

  logstash:
    container_name: logstash
    build: logstash/.
    ports:
      - "1514:1514/udp"
    volumes:
      - ${PWD}/logstash:/config
    environment:
      - XPACK_MONITORING_ENABLED=false
    command: -f /config/conf.d/* --config.reload.automatic
    restart: unless-stopped

  telegraf:
    container_name: telegraf
    build: telegraf/.
    volumes:
      - ${PWD}/telegraf/mibs:/usr/share/mibs/site
      - ${PWD}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ${PWD}/telegraf/conf.d:/etc/telegraf/telegraf.d
      - /var/run/utmp:/var/run/utmp
      - /proc:/proc
      - /sys:/sys
      - /var/run/docker.sock:/var/run/docker.sock 
    command: --config-directory /etc/telegraf/telegraf.d
    restart: always

  influxdb:
    container_name: influxdb
    build: influxdb/docker/.
    volumes:
      - influxdata_1:/var/lib/influxdb
      - ${PWD}/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    restart: always

  grafana:
    container_name: grafana
    image: "grafana/grafana:5.2.1"
    ports:
    - "3000:3000"
    volumes:
    - ${PWD}/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    - grafana-storage:/var/lib/grafana
    restart: always

#  kapacitor:
#    container_name: kapacitor
#    image: kapacitor
#    ports:
#    - "9092:9092"
#    volumes:
#    - ${PWD}/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
#    
#    restart: always

  ansible:
    container_name: ansible
    build: ansible/docker/.
    volumes:
      - ${PWD}/ansible/playbook:/etc/ansible/playbook
      - ${PWD}/ansible/hosts:/etc/ansible/hosts
      - ${PWD}/ansible/ansible.cfg:/etc/ansible/ansible.cfg
      - ${PWD}/ansible/crontab/crontab:/etc/crontab
    tty: true
    restart: unless-stopped



volumes:
  grafana-storage:
  influxdata_1:
  esdata:

networks:
  default:
