version: '3'
services:
  telegraf:
    container_name: telegraf
    image: "telegraf:latest"
    volumes:
      - ${PWD}/telegraf/mibs:/usr/share/mibs/site
      - ${PWD}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ${PWD}/telegraf/telegraf.d:/etc/telegraf/telegraf.d
    command: --config-directory /etc/telegraf/telegraf.d
    restart: always

  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    environment:
      - INFLUXDB_DB=cadvisor
    volumes:
      - ${PWD}/influxdb/data:/var/lib/influxdb
      - ${PWD}/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    restart: always

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: "grafana/grafana:latest"
    ports:
    - "3000:3000"
    volumes:
    - ${PWD}/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    - grafana-storage:/var/lib/grafana
    restart: always

volumes:
  grafana-storage:


networks:
  default:
