{
 "title": "CGNAT",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES ON telegraf FROM \"NatStats\" WITH KEY = hostname"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic Inbound",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/mams-.*\\.1/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Outbound",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/mams-.*\\.1/" }
     ]
    }
   ]
  },
  {
   "title": "MS-MPC-PIC CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_descr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "descr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jnxOperatingTable",
     "select": [
      [
       { "params": [ "jnxOperatingCPU" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "descr", "operator": "=~", "value": "/MS-MPC-PIC/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Stats addresses & ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Ports in use",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "index" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NatStats",
     "select": [
      [
       { "params": [ "jnxNatSrcNumPortInuse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Ports in use",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "index" ], "type": "tag" }
     ],
     "measurement": "NatStats",
     "query": "SELECT last(\"jnxNatSrcNumPortInuse\")/last(\"jnxNatSrcNumPortAvail\") as Percentage,last(\"jnxNatSrcNumPortAvail\") AS Total FROM \"NatStats\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"index\"",
     "select": [
      [
       { "params": [ "jnxNatSrcNumPortInuse" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Hits per second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Rule",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "index" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NatRule",
     "select": [
      [
       { "params": [ "jnxNatRuleTransHits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 35 },
   "repeat": "poolvalue",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "index" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NatPool",
     "select": [
      [
       { "params": [ "jnxNatPoolTransHits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "index" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NatStats",
     "select": [
      [
       { "params": [ "jnxNatSrcNumSessions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}